[package]
name = "eivp"
version = "0.1.0"
authors = ["mateo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"
runas = "0.2.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1