[package]
name = "eivp"
version = "0.1.0"
authors = ["Rheyskey"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
thiserror = "1.0.38"

structopt = "0.3.26"
libxbps = {path= "../libxbps"}